name: APK Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: "3.12"
  FLET_CLI_VERSION: "0.28.3"
  FLUTTER_VERSION: "3.29.2"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: stable

    - name: Install system dependencies for pyjnius
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-17-jdk-headless cython3

    - name: Accept Android SDK Licenses
      run: |
        yes | /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager --licenses

    - name: Install flet-cli ${{ env.FLET_CLI_VERSION }}
      run: |
        python -m pip install --upgrade pip
        pip install flet-cli==${{ env.FLET_CLI_VERSION }}

    - name: Build APK with Flet
      run: |
        flet build apk --verbose --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: AKBER-TIKKA-APK
        path: build/flutter/build/app/outputs/flutter-apk/app-release.apk
        if-no-files-found: error
